# Generated by Django 4.0.4 on 2022-05-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bajadery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='-', max_length=150)),
                ('ocena', models.FloatField(default=0)),
                ('lokalizacja', models.URLField(blank=True)),
            ],
        ),
    ]
