# Generated by Django 4.0.4 on 2022-05-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bajadery_lokalizacja_alter_bajadery_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajadery',
            name='adres',
            field=models.URLField(default='-'),
        ),
    ]
